apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
  labels:
    app: yolo-backend
spec:
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  # ClusterIP: solo accesible dentro del cluster (el frontend lo llama internamente)
  type: ClusterIP
