apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  labels:
    app: yolo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: yolo-frontend
          image: simon2123/yolo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              # Apunta al servicio interno del backend dentro del cluster
              value: "http://yolo-backend:8000/api/v1/detect"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10
